### ISSUE TITLE
Calculator not making requests to server

### ISSUE THREAD

**Issue by FIrgolitsch** [NiHoel/Anno1800Calculator-preview#1]
Hi!

I am noticing that the calculator preview does not send requests to the UX enhancer server, even when changing the IP in the js files. Is this just due to the fact that the enhancer isn't updated yet for the new release as well?

Kind Regards

**Comment by NiHoel** [comment]
I intentionally turned it off. I'll have to check and verify some things first. I plan the release of UXEnhancer and calculator (official update) roughly at the same time/day.

**Comment by FIrgolitsch** [comment]
I figured, thanks for confirming! Looking forward to the new release. The cleaned up codebase is looking good!
