### ISSUE TITLE
Use "old" params.js file

### ISSUE THREAD

**Issue by tefracky** [NiHoel/Anno1800Calculator-preview#2]
Hello,

this is not really an issue, but more a question/idea:

In the previous calculator version I modified the params.js to fit it to some custom mods/production speeds.

Now, the params file is implemented in the single-line calculator.bundle.js and it is no longer that easy to modify that params.

How did you generate these eval-strings? Did you used a tool for it?

As an alternative, is it possible to use the well formatted params.js in the new calculator? I know, it will be a little bit slower, but it would be ok for me. 

I am not that familiar with JavaScript, so if anyone has some lines to implement the old params.js, i.e. replace the eval part for the params to refer dynamically to the params.js, would be very helpful!

Thanks!

**Comment by NiHoel** [comment]
Hello,

The bundle is built with `webpack`. I uploaded a `package.json` with which you can set up a node environment.

However, a much easier way is to modify the well-formatted `js/params.js` and included it in `index.html`:
<pre><script src="js/params.js"></script>
<script src="dist/calculator.bundle.js"></script>
</pre>

(I pusehd an update a few minutes ago such the bundle does not overwrite the params file included before.)

**Comment by tefracky** [comment]
It works as exceptet, thanks a lot!

Merry Christmas
